listen_addr: ":8080"
routes:
  "/users":
    middlewares:
      - "Recover"
      - "Logging"
      - "RequestID"
      - "Metrics"
      - "RateLimit"
      - "Auth"
    backends:
      - "http://mock-backends:8081"
      - "http://mock-backends:8082"
      - "http://mock-backends:8083"
  "/billings":
    middlewares:
      - "Recover"
      - "Logging"
      - "RequestID"
      - "Metrics"
      - "RateLimit"
      - "Auth"
    backends:
      - "http://mock-backends:8084"
      - "http://mock-backends:8085"